#!/bin/bash

# Grafana development machine settings
# This file is loaded automatically when ~/env/.grafana-machine marker file exists
# Used for Grafana development (cloud or local)

# Increase JavaScript heap size to 10GB (needed for giant project like Grafana)
export NODE_OPTIONS="--max-old-space-size=10240"

# Grafana setup
export GF_DEFAULT_APP_MODE=development

export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH