#!/bin/sh

[ -r /etc/sysconfig/i18n ] && . /etc/sysconfig/i18n
export LANG
export SYSFONT
# Disable lockscreen
gconftool-2 --set /apps/gnome-screensaver/idle_activation_enabled --type boolean false &
# Enable shared clipboard in background
vncconfig -nowin -SendPrimary=0 &
# Disable annoying updater popup
(sleep 5; killall gpk-update-icon) &
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
if [ -x /etc/X11/xinit/xinitrc ]; then
  exec /etc/X11/xinit/xinitrc
fi
if [ -f /etc/X11/xinit/xinitrc ]; then
  exec sh /etc/X11/xinit/xinitrc
fi
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources